# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334ec5289d00ded6f644723a2d748ae617b43aed5aab4efe88fe15c9a1eef9dca7e76f473da5765a134ed5567e17a0f8004cb0e1909b961081b9fcb651ed2c82

test:
  secret_key_base: 983e44f6f5c5cf1a5c8f51e9b517cb214c9be4fd1c9b75e09a98e10ac468cd9079759c333b8a2d3a9cfef9ddb81fcb3f45aede12122074c8b319883fb70f75e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
